import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import path from "node:path";

import {
  parseTabulateBenchmarkArgs,
  validateTabulateBenchmarkPayload,
} from "./tabulateViewportBenchmarkCore.mjs";

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const options = parseTabulateBenchmarkArgs(process.argv.slice(2));
const native = spawnSync(
  "cargo",
  [
    "run",
    "--quiet",
    "--example",
    "performance_baseline",
    "--features",
    "perf-harness",
    "--",
    "--operation",
    "tabulate",
    "--rows",
    String(options.sourceRows),
    "--columns",
    String(options.logicalCells),
    "--runs",
    String(options.samples),
  ],
  {
    cwd: path.join(repositoryRoot, "src-tauri"),
    encoding: "utf8",
    maxBuffer: 16 * 1024 * 1024,
  },
);

if (native.error) {
  throw native.error;
}
if (native.status !== 0) {
  process.stderr.write(native.stderr);
  throw new Error(`Native Tabulate benchmark exited with status ${native.status}`);
}

const nativeReport = parseNativeReport(native.stdout);
if (!nativeReport.tabulate) {
  throw new Error("Native Tabulate benchmark did not return a tabulate report");
}

const payload = {
  ...nativeReport.tabulate,
  qualification: options.qualification,
  ipcRoundTripMs: { status: "unmeasured", samples: [] },
  visibleInteractionMs: { status: "unmeasured", samples: [] },
};
const validation = validateTabulateBenchmarkPayload(payload);
const report = {
  fixture: {
    sourceRows: options.sourceRows,
    logicalCells: options.logicalCells,
    samples: options.samples,
    provenance: "deterministic DuckDB range generated by the native performance harness",
  },
  payload,
  validation,
};

process.stdout.write(`${JSON.stringify(report, null, 2)}\n`);
if (!validation.valid) {
  process.exitCode = 1;
}

function parseNativeReport(stdout) {
  const lines = stdout.split(/\r?\n/u).map((line) => line.trim()).filter(Boolean);
  for (let index = lines.length - 1; index >= 0; index -= 1) {
    try {
      return JSON.parse(lines[index]);
    } catch {
      // Cargo may emit non-JSON status lines before the report.
    }
  }
  throw new Error("Native Tabulate benchmark produced no JSON report");
}
